grinnellplans/GrinnellPlans

app/helpers/application_helper.rb, app/views/layouts/_autofinger.html.haml, app/views/layouts/_links.html.haml
We add these CSS classes to a number of lists in the interface. This extracts the logic into a helper for maximum convenience.
=> Helper to add odd/even/first/last CSS classes

app/controllers/preferences/avail_links_controller.rb, app/models/avail_link.rb, app/views/layouts/_links.html.haml, app/views/preferences/avail_links/show.html.haml, config/routes.rb, db/migrate/20150912233905_add_rails_helper_to_avail_links.rb, db/schema.rb, spec/controllers/avail_links_controller_spec.rb, spec/factories.rb
Fetching the user preferences for optional links from the DB. Had to add a DB column to store the rails helper, since the old HTML snippets hold paths that are no good to us any more.
=> Links conversion

db/seed/development/avail_links.yml
=> Update link seeds to include rails helpers

app/controllers/account_sessions_controller.rb, spec/controllers/account_sessions_controller_spec.rb
Issue #3  Test logout functionality
=> Test logout and add strong_params

README.rdoc, db/seed/development/accounts.yml
* Updates to the Readme
* Updating the account seeds to be more readable
=> Documentation improvements

app/helpers/application_helper.rb, app/models/account.rb, app/models/avail_link.rb, app/models/concerns/links.rb, app/views/layouts/_links.html.haml, config/routes.rb, spec/requests/user_registration_spec.rb
=> Add permanent links to navigation

app/helpers/application_helper.rb, app/views/_flash_message.html.haml, app/views/_info_message.html.haml, app/views/layouts/application.html.haml, app/views/secrets/index.html.haml
=> Info messages and flash messages

app/models/viewed_secret.rb, spec/models/viewed_secret_spec.rb
I'm so rusty on Rails stuff...but fixes #41
=> Validate that ViewSecret has an account

app/models/poll_vote.rb, spec/models/poll_vote_spec.rb
=> Validate that PollVote has an account

app/controllers/application_controller.rb, app/helpers/autofinger_helper.rb, app/views/layouts/_autofinger.html.haml, spec/controllers/application_controller_spec.rb
Autofinger displays all levels to match current behavior. Now uses correct classes for current priority level.
=> Autofinger styling fixes

app/assets/stylesheets/libre.css, app/views/layouts/_search.haml, app/views/layouts/application.html.haml
A couple subtle alterations to the HTML structure to match the PHP version, and updates to `libre.css` (pulled over from what's currently live).
=> Fix libre.css and search styling

spec/controllers/account_sessions_controller_spec.rb, spec/controllers/admin/secrets_controller_spec.rb, spec/factories.rb, spec/models/poll_vote_spec.rb, spec/models/secret_spec.rb, spec/models/viewed_secret_spec.rb
A few fixes from Rubocop. I'm still hoping to get an automated PR checker up soon to watch for these.
=> Rubocop corrections

README.rdoc
Quick update (mostly I want to see if Travis builds this PR).
=> Update rubocop path in README

app/models/account.rb, app/models/plan.rb, spec/controllers/plans_controller_spec.rb
I'm surprised this didn't exist yet…
=> Update autofingers on plan update

app/controllers/preferences/account_details_controller.rb, app/views/preferences/account_details/show.html.haml, config/routes.rb, spec/controllers/preferences_account_details_controller_spec.rb
=> Preferences: account details

app/controllers/application_controller.rb, app/controllers/plans_controller.rb, app/controllers/preferences/account_details_controller.rb, app/controllers/preferences/display_controller.rb, app/controllers/secrets_controller.rb, app/views/layouts/_autofinger.html.haml, spec/controllers/application_controller_spec.rb
Just a little cleanup to simplify loading autofinger records.
=> Modify autofingers helper

app/controllers/account_sessions_controller.rb, app/controllers/accounts_controller.rb, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/password_resets_controller.rb, app/controllers/plans_controller.rb, app/controllers/preferences/account_details_controller.rb, app/controllers/preferences/display_controller.rb, app/controllers/secrets_controller.rb
Unauthenticated pages are now opt-out, since this is a better direction in which to make mistakes.
=> Require user by default

app/controllers/preferences_controller.rb, app/models/concerns/links.rb, app/views/preferences/index.html.haml, config/locales/en.yml, config/routes.rb
Adds a main Preferences page to link to the others.
=> Add base preferences page

Gemfile, Gemfile.lock, app/assets/stylesheets/administrate/application.scss, app/assets/stylesheets/administrate/custom.scss, app/assets/stylesheets/administrate/filters.scss, app/views/admin/secrets/_collection.html.erb, app/views/admin/secrets/index.html.erb, config/routes.rb
* Update routes to use new administrate config.
* Update custom CSS to use new administrate CSS and be generally cleaner.
=> Upgrade administrate gem

app/assets/stylesheets/administrate/base/_forms.scss, app/assets/stylesheets/administrate/base/_layout.scss, app/assets/stylesheets/administrate/base/_lists.scss, app/assets/stylesheets/administrate/base/_tables.scss, app/assets/stylesheets/administrate/base/_typography.scss, app/assets/stylesheets/administrate/components/_app-container.scss, app/assets/stylesheets/administrate/components/_attributes.scss, app/assets/stylesheets/administrate/components/_buttons.scss, app/assets/stylesheets/administrate/components/_cells.scss, app/assets/stylesheets/administrate/components/_field-unit.scss, app/assets/stylesheets/administrate/components/_flashes.scss, app/assets/stylesheets/administrate/components/_form-actions.scss, app/assets/stylesheets/administrate/components/_header.scss, app/assets/stylesheets/administrate/components/_main-content.scss, app/assets/stylesheets/administrate/components/_pagination.scss, app/assets/stylesheets/administrate/components/_search.scss, app/assets/stylesheets/administrate/components/_sidebar.scss, app/assets/stylesheets/administrate/components/_table.scss, app/assets/stylesheets/administrate/library/_data_label.scss, app/assets/stylesheets/administrate/library/_variables.scss
I think I goofed while testing and used a different version of the gem. Had to add a bunch of stuff to prevent Sass from erroring.
=> Fix administrate SCSS

app/controllers/plans_controller.rb, app/views/layouts/_search.haml, app/views/plans/search.html.haml, spec/controllers/plans_controller_spec.rb
=> Basic search functionality
